version: '3.8' 
services: 
  db: 
    image: postgres:14 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/ 
    environment: 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=pdf_manager 
    ports: 
      - "5432:5432" 
  backend: 
    build: ./backend 
    volumes: 
      - ./backend:/app 
    ports: 
      - "8000:8000" 
    depends_on: 
      - db 
    environment: 
      - DATABASE_URL=postgresql://postgres:password@db/pdf_manager 
volumes: 
  postgres_data: 
